server:
  port: 7782
  servlet:
    context-path: /api
spring:
  jpa:
    properties:
      hibernate:
        default_schema: idp
        jdbc:
          lob:
            non_contextual_creation: 'true'
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5454/bza
    password: 45EO3PDBS2
    username: app
    schema: idp
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: '20000'
      idle-timeout: '10000'
      maximum-pool-size: '40'
      auto-commit: 'true'
      minimum-idle: '10'

jwt:
  secret: RXN0aGVyemluaGFBbW9yRGFNaW5oYVZpZGE=
  expiration_ms: 86000000
  auth:
    converter:
      resource-id: idp
      principal-attribute: principal_username

keycloak:
  url: http://localhost:8084/realms/brazona
  name: idp
  grant: password
  client:
    id: idp
    secret: DhlCtfWsVdblABfje3scJR5bQEv8O3yi

logging:
  file:
    name: myapp.log
    max-size: 10MB
    max-history: 10
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
  level:
    root: WARN
    org:
      hibernate: INFO
      springframework:
        security: DEBUG
        data: INFO
        web: INFO
    br:
      brazona:
        idp:
          api: DEBUG  
