# Copyright 2024 Brazona Tech

##################################################################################################
# Details service
##################################################################################################
# Incluí credenciais de acesso do Github ao ambiente Kubernets com a finalidade de usar-la no 
# download das imagens docker

---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerconfigjson-github-com
  namespace: homologation
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJRMlY2WVhKR1pXeHBjR1U2WjJod1gzQktUMEpEWWpWSFNqZHBTREYyUTNKRFUwVjBja00wYkdKaVJHUkxVVEkyY1dwVWRRPT0ifX19
