kind: ConfigMap
apiVersion: v1
metadata:
  name: config-server
  namespace: production
data:
  SPRING_ACTIVE_PROFILE: prd
  GITHUB_TOKEN: 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
  GITHUB_USER: CezarFelipe
  CONFIG_SERVER_PASS: SbfZLn57ZW
  CONFIG_SERVER_ENCRYPT_KEY: JBK9Y8K06XDO
  GITHUB_BRANCH: main